apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
spec:
  giteaImageTag: latest
  giteaVolumeSize: 8Gi
  giteaSsl: true
  postgresqlVolumeSize: 8Gi
  giteaAdminUser: admin
  giteaAdminEmail: admin@redhat.com
  giteaAdminPassword: openshift
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user%d"
  giteaUserNumber: TOTAL_USER
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://gitlab.com/ocp-demo/frontend-js.git
    name: frontend-js
    private: false
  - repo: https://github.com/rhthsa/simple-rest-go.git
    name: simple-rest-go
    private: false
  - repo: https://gitlab.com/ocp-demo/backend_quarkus.git
    name: backend_quarkus
    private: false        