apiVersion: v1
kind: Namespace
metadata:
  name: openshift-builds
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-builds-operator
  namespace: openshift-builds
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-builds-operator
  namespace: openshift-builds
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-builds-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
